name: CI

on: [push, pull_request]

env:
  NODE_VERSION: '20.11'
  GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
  GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
  GOOGLE_REDIRECT_URI: ${{ secrets.GOOGLE_REDIRECT_URI }}

jobs:
  test:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - id: auth
        uses: google-github-actions/auth@v2
        with:
          service_account: ${{ secrets.GOOGLE_SERVICE_ACCT }}
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
          create_credentials_file: true
          project_id: 'cht-config-library'
          token_format: access_token
          access_token_scopes: https://www.googleapis.com/auth/drive.readonly
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
#      - run: cp ${{ steps.auth.outputs.credentials_file_path }} .gdrive.session.json
      - run: echo "NOW=$(date +%s)" >> $GITHUB_ENV
      - run: |
          echo '{
            "access_token": "${{ steps.auth.outputs.access_token }}",
            "scope": "https://www.googleapis.com/auth/drive.readonly",
            "token_type": "Bearer",
            "expiry_date": "9999999999999"
          }' > google-drive/.gdrive.session.json
      - run: sudo python -m pip install git+https://github.com/medic/pyxform.git@medic-conf-1.17#egg=pyxform-medic
      - run: sudo apt install -y xsltproc
      - run: npm ci
      - run: npm run lint
      - run: npm test
