name: CI

on: [push, pull_request]

env:
  NODE_VERSION: '20.11'
  GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
  GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
  GOOGLE_REDIRECT_URI: "http://localhost"
  GOOGLE_TOKEN_SCOPE: 'https://www.googleapis.com/auth/drive.readonly'

jobs:
  test:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - id: auth
        uses: google-github-actions/auth@v2
        with:
          service_account: ${{ env.GOOGLE_SERVICE_ACCT }}
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
          project_id: 'cht-config-library'
          token_format: access_token
          access_token_scopes: ${{ env.GOOGLE_TOKEN_SCOPE }}
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Write token to google-drive/.gdrive.session.json file
        run: |
          echo '{
            "access_token": "${{ steps.auth.outputs.access_token }}",
            "scope": "${{ env.GOOGLE_TOKEN_SCOPE }}",
            "token_type": "Bearer",
            "expiry_date": "9999999999999"
          }' > google-drive/.gdrive.session.json
      - run: sudo python -m pip install git+https://github.com/medic/pyxform.git@medic-conf-1.17#egg=pyxform-medic
      - run: sudo apt install -y xsltproc
      - run: npm ci
      - run: npm run lint
      - run: npm test
